Repository aws/aws-lambda-dotnet, pull requests merged in 2023-02, with the labels that each got.

#1066 Add APIGatewayCustomAuthorizer V2 requests
  Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerV2IamResponse.cs
  Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerV2Request.cs
  Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerV2SimpleResponse.cs
  Libraries/test/EventsTests.Shared/EventTests.cs
  Libraries/test/EventsTests.Shared/EventsTests.Shared.projitems
  Libraries/test/EventsTests.Shared/custom-authorizer-v2-iam-response.json
  Libraries/test/EventsTests.Shared/custom-authorizer-v2-request.json
  Libraries/test/EventsTests.Shared/custom-authorizer-v2-simple-response.json
Labels: feature-request

#1073 feat: Add POCOs for S3 object events
  Libraries/src/Amazon.Lambda.CloudWatchEvents/S3Events/Bucket.cs
  Libraries/src/Amazon.Lambda.CloudWatchEvents/S3Events/S3Object.cs
  Libraries/src/Amazon.Lambda.CloudWatchEvents/S3Events/S3ObjectCreate.cs
  Libraries/src/Amazon.Lambda.CloudWatchEvents/S3Events/S3ObjectCreateEvent.cs
  Libraries/src/Amazon.Lambda.CloudWatchEvents/S3Events/S3ObjectDelete.cs
  Libraries/src/Amazon.Lambda.CloudWatchEvents/S3Events/S3ObjectDeleteEvent.cs
  Libraries/src/Amazon.Lambda.CloudWatchEvents/S3Events/S3ObjectEventDetails.cs
  Libraries/src/Amazon.Lambda.CloudWatchEvents/S3Events/S3ObjectRestore.cs
  Libraries/src/Amazon.Lambda.CloudWatchEvents/S3Events/S3ObjectRestoreEvent.cs
Labels: feature-request, response-requested, pr/needs-review

#733 Support Cognito Pre Token Generation Event
  Libraries/src/Amazon.Lambda.CognitoEvents/LambdaTriggerEvents/Base/CallerContext.cs
  Libraries/src/Amazon.Lambda.CognitoEvents/LambdaTriggerEvents/Base/TriggerEvent.cs
  Libraries/src/Amazon.Lambda.CognitoEvents/LambdaTriggerEvents/Base/TriggerRequest.cs
  Libraries/src/Amazon.Lambda.CognitoEvents/LambdaTriggerEvents/Base/TriggerResponse.cs
  Libraries/src/Amazon.Lambda.CognitoEvents/LambdaTriggerEvents/PreTokenGenerationTrigger/ClaimsOverrideDetails.cs
  Libraries/src/Amazon.Lambda.CognitoEvents/LambdaTriggerEvents/PreTokenGenerationTrigger/GroupConfiguration.cs
  Libraries/src/Amazon.Lambda.CognitoEvents/LambdaTriggerEvents/PreTokenGenerationTrigger/GroupOverrideDetails.cs
  Libraries/src/Amazon.Lambda.CognitoEvents/LambdaTriggerEvents/PreTokenGenerationTrigger/PreTokenGenerationEvent.cs
  Libraries/src/Amazon.Lambda.CognitoEvents/LambdaTriggerEvents/PreTokenGenerationTrigger/PreTokenGenerationRequest.cs
  Libraries/src/Amazon.Lambda.CognitoEvents/LambdaTriggerEvents/PreTokenGenerationTrigger/PreTokenGenerationResponse.cs
  Libraries/test/EventsTests.Shared/EventTests.cs
  Libraries/test/EventsTests.Shared/EventsTests.Shared.projitems
  Libraries/test/EventsTests.Shared/cognito-pre-token-generation-event.json
Labels: feature-request

#899 AspNetCoreServer: make adding exception detail to http response opt-in
  Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs
  Libraries/test/Amazon.Lambda.AspNetCoreServer.Test/TestApiGatewayHttpApiV2Calls.cs
  Libraries/test/Amazon.Lambda.AspNetCoreServer.Test/TestCallingWebAPI.cs
Labels: bug

#1432 Add common 5xx status codes to HttpResults for Annotations framework
  Libraries/src/Amazon.Lambda.Annotations/APIGateway/HttpResults.cs
  Libraries/test/Amazon.Lambda.Annotations.SourceGenerators.Tests/HttpResultsTest.cs
Labels: bug, pr/needs-review, xs
